### ISSUE TITLE
Lantern Pi: excessive log info

### ISSUE THREAD

**Issue by doodle8866** [vimagick/rpi-bin#1]
Hi, I've been using your lantern binary on my rpi for some time. It worked like a charm, except that I recently found over 90% of my system log came from lantern flashlight even when no requests were made at all. Could you please also bulid a release version as well. Thanks a million!

**Comment by vimagick** [comment]
You can disable logging via creating `/etc/systemd/system/lantern.service.d/override.conf`

``` ini
[Service]
StandardOutput=null
StandardError=null
```

Then run these commands:

``` bash
systemctl daemon-reload
systemctl restart lantern
```

You can still access lantern log at `/root/.lantern/logs/lantern.log`.

I hope it will work.

**Comment by eveloson** [comment]
请问下，我在树莓派上装了kali，但是安装lantern.deb后/etc/systemd/system下并没有lantern.service ，不兼容吗，只能用在raspbian上？

**Comment by vimagick** [comment]
@eveloson: 请运行下面的命令

```
systemctl cat lantern
```

该文件位于 `/lib/systemd/system/lantern.service`

**Comment by eveloson** [comment]
还是不行，存在这个/lib/systemd/system/lantern.service文件，但是systemctl cat lantern提示找不到，直接 /usr/bin/lantern也提示找不到， 但/usr/bin/lantern的确存在

**Comment by vimagick** [comment]
@eveloson 你用的是最新版raspbian系统吗？
我在pi1/pi2/pi3上测试都正常。

**Comment by vimagick** [comment]
@eveloson
不好意思，刚看到你用的是kali。
暂时还没在kali上测试过。

**Comment by eveloson** [comment]
kali跟raspbian不都是基于debian么，难道因为内核版本不同

**Comment by vimagick** [comment]
@eveloson 请在pi3上执行下面的命令

``` bash
$ uname -m
armv7l
```

可以看到：Raspbian仍然使用armv7内核，虽然CPU支持armv8。

**Comment by eveloson** [comment]
kali也是armv7l，还有请问下我用make docker-linux-arm编译的时候 docker会下载fedora image不知道什么原因，请问你的docker是如何设置的，实在不行只能尝试在pi上编译了

**Comment by vimagick** [comment]
@eveloson 编译lantern, 请参考 https://github.com/vimagick/rpi-bin/wiki/lantern

**Comment by eveloson** [comment]
3Q,解决了一行，语句搞定
ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3

**Comment by vimagick** [comment]
@eveloson Good news 👍
