### ISSUE TITLE
The newest lantern_2.2.4-1_armhf systemd service file should be changed

### ISSUE THREAD

**Issue by gocoolshj4** [vimagick/rpi-bin#2]
the original 'ExecStart=/usr/bin/lantern -addr=0.0.0.0:8787' should be changed to 'ExecStart=/usr/bin/lantern-2.2.4-armv6h -addr=0.0.0.0:8787' for there is no such file as 'lantern' in folder /usr/bin.Or it won't get started.
I wonder if it is possible to build lantern on raspberry pi, I tried several times but failed.It seems that the golang only works well with amd64 processor,some problem occurs when running on raspberry pi.
So if it is the only possible solution to do cross-compile on PCs to make a deb compatible with pi?
Thanks a lot for your contribution！This deb works perfectly on my pi3!

**Comment by vimagick** [comment]
You can read this guide to build lantern on x86 machine: https://github.com/vimagick/rpi-bin/wiki/lantern

**Comment by vimagick** [comment]
I've fixed this problem, please download it again. Thanks!
